### ISSUE TITLE
As a user, I want to receive the emails TDS says they sent

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#100]
I looked for an existing issue but couldn't find it. One thing that @orlando brought up in a call was the issue of emails bouncing, which flags us as possible spammers, resulting in emails not being received. One thing we might look at in solving this problem is Discourse's "bounce score": https://meta.discourse.org/t/bounce-score-setting-description/44125

**Comment by orlando** [comment]
I think this won't be a problem when we switch all communications to happen through Discourse PMs. But let's test with different email providers (like outlook, yahoo, google etc)

**Comment by orlando** [comment]
I'll close this, we won't have this issue with Discourse.
