### ISSUE TITLE
ATB - False Cert. duplicate school start date fields

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#109]
The personal information form for the wage garnishment dispute tool collects the date range for when the member began and stopped attending the school. Later, we ask for the start date again during the False Certification - Ability to Benefit form. We should get rid of that field and reuse the input from the previous field.

**Comment by orlando** [comment]
**School section**
![image](https://user-images.githubusercontent.com/849872/52825207-76968080-3081-11e9-99b1-36de4e43745b.png)

**False certification - Ability to benefit section**
![image](https://user-images.githubusercontent.com/849872/52825244-92018b80-3081-11e9-9ca6-9b2a9a26fd75.png)
