### ISSUE TITLE
ATB - False Cert. confusing wording when answer make member inelligible

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#110]
![Screen Shot 2018-04-15 at 5.15.00 PM.png](https://images.zenhubusercontent.com/58c866b151aa2c3057787927/d5c16424-5ec5-45ea-a042-efdac2201d51)

@annlarson Any guidance on what this should read to make it clearer?

**Comment by annlarson** [comment]
Hmmm. What is confusing about this? It makes sense to me.

**Comment by orlando** [comment]
I think looks good too, I'll close this
