### ISSUE TITLE
Reimplement view own disputes functionality

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#111]
This functionality was mistakenly removed when we stripped out the authentication and user profile information from the dispute-tools service. We need to reimplement this feature in the new tools or else as part of the dashboard/hub.

**Comment by marcondag** [comment]
@shoshber @orlando @stephenkistner What do y'all thing re: restoring this in the new tools or having it be part of the dashboard? Reverting the changes in the dispute-tools would be less work but would further fragment the center of user profile information.

**Comment by orlando** [comment]
@marcondag I think we should leave this in the Dispute Tools (when you go to your profile), and expose an endpoint to query from other services.
