### ISSUE TITLE
User should be able to upload a profile image

### ISSUE THREAD

**Issue by sarayourfriend** [debtcollective/parent#12]
In gitlab by @marcondag on Feb 19, 2018, 15:01

As a User, I want to be able to upload a profile image, so it doesn't use the default one

## Acceptance Criteria

- [ ] After the user signs up, it should be taken to their profile
- [ ] From the profile page, user can upload a new image
- [ ] Uploads will store in AWS S3

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 15:08

mentioned in issue #9

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 19, 2018, 15:21

changed title from **User sho{-w-} be able to upload a profile image** to **User sho{+uld+} be able to upload a profile image**

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:13

Closing to use Discourse as SSO/user-profile provider

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:13

closed
