### ISSUE TITLE
Change "bookmark" copy for meetups and actions

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#127]
# Acceptance Criteria
- [ ] write a plugin that can assign/identify topic as either events or actions
  - not all actions and events will be `discourse-events` events (`discourse-events` identifies topics as events based on the existence/value of the `start_time` custom field)
- [ ] change the "bookmark"ing of a event to be "RSVP"
- [ ] change the "bookmark"ing of an action to be "I'm doing this"?

**Comment by shoshber** [comment]
The bookmark functionality comes from discourse core, not the plugin.

The best way to do this, I think, is in a second plugin. It would add two boolean custom fields to discourse Topics, 'meetup', and 'action'. We can then extend discourse to replace "bookmark" copy with "RSVP"/"I'm doing this" as appropriate.

**Comment by marcondag** [comment]
Sounds good to me

**Comment by shoshber** [comment]
we could automatically tag actions with a "global" tag or something

**Comment by shoshber** [comment]
You know what, I don't think we should do this at all. The plugin author is intending to add an RSVP feature, although no word as to when (https://meta.discourse.org/t/events-plugin-calendar/69776/208). In the meantime, someone suggested using a poll to handle RSVPs, which I think is really clever: https://meta.discourse.org/t/events-plugin-calendar/69776/197 .

If we do need the RSVP feature (with notification settings) before the plugin author can get to it, I think modding the polls plugin might be better than modding core discourse. Presumably someone might want to bookmark a topic without RSVP-ing, or vice versa. Also, it turns out you bookmark posts, not topics, which makes the "actions and meetups are types of topics" model muddy.
