### ISSUE TITLE
Add an event and action category per collective

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#129]
# Acceptance Criteria

- [x] Add an event and action category per collective
    * Events and Actions are sub-categories of the collective categories
- [x] Restrict permissions of events to only members of the collective + administrators
- [x] Allow all Debt Collective members to see and participate in discussions about Actions; only admins can create
- [x] Fix up  `discourse-node-api`
- [x] Testing

**Comment by shoshber** [comment]
I'm actually not so sure about this--will think about it

**Comment by marcondag** [comment]
IIRC there's at least something where sub categories cannot have less restrictive permissions than the parent category, in which case the events could live under the collective category but the actions could not. On the other hand, we _could_ change the model slightly and add a discussion category to each collective category and make the collective and its actions sub category open with the discussion and events sub categories being closed. The ACL would look like this:

```
Collective (Parent Category) - PUBLIC
  Actions (Sub category) - PUBLIC
  Events (Sub category) - Admins + collective members only
  Discussion (Sub category) - Admins + collective members only
```

**Comment by marcondag** [comment]
Would topic templates for events and actions mean we wouldn't have to do the guided event creation?

**Comment by shoshber** [comment]
I was reading abut the plugin. I don't think we need to make subcategories. We just have to enable the events plugin for each collective, and add a link at the top to all the meetups and all the actions.

**Comment by marcondag** [comment]
How would we restrict events and actions differently?

**Comment by shoshber** [comment]
Remind me why we want to do that?

**Comment by shoshber** [comment]
we could automatically tag actions with a "global" tag or something, to allow everyone to see/participate in them

**Comment by marcondag** [comment]
And that will override the category's permissions?




On Sun, Apr 29, 2018 at 9:26 PM -0400, "Shoshana Berleant" <notifications@github.com> wrote:












we could automatically tag actions with a "global" tag or something, to allow everyone to see/participate in them

**Comment by marcondag** [comment]
Well, the idea behind the categories was that it silos the information into some easy to manage categories. Any admin can understand that if a member wants to be in a collective you just add them to the group. But if there's a better way and we can implement it in time then let's do it! Though I suspect the events plugin does this using normal Rails ACL. Curious to see what you find. 

And yes, one of the requirements for actions is that they are open. If the global tag overrides the categories permissions then that would be fine as long as you can extend the events plugin.

**Comment by shoshber** [comment]
maybe actions shouldn't be in categories? The whole point of the categories is to limit who can see what, right?

**Comment by shoshber** [comment]
Looks like subcategories don't inherit permissions from their supercategories: https://meta.discourse.org/t/subcategories-do-not-inherit-permissions-from-parent-category/17174

**Comment by shoshber** [comment]
Ah, I remember why we wanted Events to be in their own categories--because "Topic Templates" are defined per category, and we want to use the topic templates as a step toward a guided event creation process.

**Comment by marcondag** [comment]
The other motivation was that events and actions need to be related to a collective and the easiest way to do that is to have them contained within the collective category. But to manage the permissions separately we need the sub category. At least for Actions. Maybe we don't for Events but it seems short sighted to not split these things into sub categories when it only enhances our permissions model and gives us greater access/ability to select data from discourse's API. After all, it's trivial to retrieve a list of topics for a category. Would be great for other services to be able to efficiently say give me all the events for the student debt collective without having to consider the specific implementation details of the events plugin.

**Comment by shoshber** [comment]
@marcondag Writing a filter for topics is very simple--in fact I've already done it while I was exploring earlier today.

It's not necessarily an enhancement to the permissions model, if it adds complexity that we don't (will never?) need.

The existence of the subcategories is visible to users, and making a UI decision based on programmatic needs feels weird to me. But perhaps it is a UI enhancement?

Adding identical subcategories to each collective isn't DRY, but a little dampness is probably ok, as y'all have pointed out to me in the past.

re: enhancing permissions model, that is an excellent point. Very important for Actions. For Meetups, though, it isn't necessary, because our permissions for meetups and discussion are the same, as far as I know, but that leads to the question:

Do you recall the permissions scheme for meetup and action **creation**? It appears that we did not document those permissions--or are they same as reading/participating?

(for future reference: turns out one can define topic templates by url, so they aren't necessarily bound to categories: https://meta.discourse.org/t/what-are-topic-templates/38295)

I'm leaning toward one Actions subcategory per collective, and no Meetups subcategories.

**Comment by shoshber** [comment]
https://github.com/debtcollective/discourse-seed/pull/9

**Comment by shoshber** [comment]
:( subcategories with more permissive permissions than their parent categories aren't supported?

https://meta.discourse.org/t/child-category-seems-to-inherit-part-of-the-permissions-in-the-parent-category/84493/3

**Comment by marcondag** [comment]
Yes, I think this is why I suggested having discussion in its own subcategory so that each collective can be visible to all and then just events (or actions, I forget which is hidden) and discussions be hidden while the other is visible. 

This would also solve the problem of figuring out where to link people for the collectives in the header. This way they would see at least the collective and the one publicly visible subcategory even if they're not logged in/a member of that collective.

**Comment by shoshber** [comment]
> This would also solve the problem of figuring out where to link people for the collectives in the header. This way they would see at least the collective and the one publicly visible subcategory even if they're not logged in/a member of that collective.

Excellent point!

> Yes, I think this is why I suggested having discussion in its own subcategory so that each collective can be visible to all and then just events (or actions, I forget which is hidden) and discussions be hidden while the other is visible.

This would work really well as long as there is a way to prevent new topics being created inside a collective category that are not in a subcategory. I will investigate.

**Comment by shoshber** [comment]
Wait, but @annlarson and Laura wanted the existence of the other collectives to be hidden, right?

**Comment by marcondag** [comment]
That's not possible if actions are public, right?

**Comment by shoshber** [comment]
I suppose actions could be public, but their relationship to other collectives could be hidden?

**Comment by shoshber** [comment]
https://github.com/debtcollective/parent/issues/163
