### ISSUE TITLE
Members should be able to edit their profile information

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#13]
In gitlab by @marcondag on Feb 19, 2018, 15:08

As a debt collective member I want to be able to edit my profile information so that if my information changes then my profile is in sync

## Tasks

- [ ] Change password by providing the current password
- [ ] Change any profile field
- [ ] Change profile picture
- [ ] Accessible only by user

## Assumptions

1. There is a way to upload and save profile pictures (#8)

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 19, 2018, 15:19

changed the description
