### ISSUE TITLE
Implement Theme header in Discourse

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#139]
With https://github.com/debtcollective/discourse-debtcollective-theme/pull/2, we added the base styling for Discourse.

We still need to implement the header links so it looks like the rest of the Debt Collective sites. The links we need to add are the ones from the Dispute Tools header.

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/a669a870-ef40-462b-adb9-679580bf2fab)

Right now the **My Disputes** link is really important and we need to show it everywhere, this link will take you back to the **My Disputes** view in the tools app.

## Tasks

- [ ] Add links to the Discourse header via plugin
- [ ] Make sure it renders correctly in small screens.

## Acceptance

- Users should see the links that are in the Dispute Tools header in Discourse
- Users should be able to use the links to move between services in Discourse

**Comment by shoshber** [comment]
We are planning to replace discourse's header with `dc-vue-header`, is that correct?

**Comment by orlando** [comment]
No, we will just implement the links and the style, the functionality will stay the same 

Enviado desde mi iPhone
