### ISSUE TITLE
set up continuous integration for all repos

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#141]
CircleCI/other integration so all pull requests go through a quality control

Also: 
"This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0."

**Comment by shoshber** [comment]
`discourse-seed` does? I guess I meant "continuous integration" after all. What I'm really after is the integration with circle where the pull request can't be merged without a successful test run

**Comment by marcondag** [comment]
Oh oh oh. Yeah. I guess we'd have to see what all tests we can write for all of them that don't have it.

**Comment by marcondag** [comment]
Discourse seed's probably doesn't work anymore? Not sure if the API keys need to be updated between our redeployments/if we've redeployed without updating the keys.
