### ISSUE TITLE
`discourse-seed` cannot update groups

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#142]
Reproduce:

1. Check out `discourse-seed` and uncomment the update groups line in `seeds/collectives.js`
1. Run `discourse-seed` on a brand-new discourse. It is now populated with all the groups.
2. Edit one of the properties of `collectiveGroupDefaults` (e.g. `visibility_level`)
3. Re-run `discourse-seed`. It will fail with a 404: `The action \'update\' could not be found for Admin::GroupsController`

## Acceptance criteria
- [ ] An edited group can be updated using the seed script

Since this is unlikely to actually come up in production, this is low-priority.

**Comment by marcondag** [comment]
`discourse-seed` is deprecated and this has been fixed with the `discourse-import`
