### ISSUE TITLE
Migrate data to new dispute tools

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#144]
In order to use the new dispute tools, we need to migrate the data from the current version to the new one. Admins and Users should be able to use the system and see the data

## Acceptance criteria

- [x] Migrate data from current dispute tools to the new version (tools.debtsyndicate.org)
- [x] Write documentation on how to do it.

**Comment by marcondag** [comment]
Please see #158 for further work that is necessary before this can be considered completed.

**Comment by orlando** [comment]
Documentation is in the [discourse-import](https://github.com/debtcollective/discourse-import)
