### ISSUE TITLE
SSO nonce validation fails on refresh

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#145]
Reproduce:
1. Log in to dispute-tools
2. Navigate to a page with `sso=xxxxxx` in lthe url (e.g. make a new dispute)
3. Refresh the page (ctrl-r)
4. The page hangs indefinitely, indicating an SSO error (see https://github.com/debtcollective/parent/issues/143)

A similar problem will occur if someone bookmarks a URL with `sso=xxxxx` and attempts to retrieve it later.
 
## Acceptance criteria

Acceptance criteria is a checklist stating how the correct behavior of this ticket will look like, some examples are:

- [ ] Urls do not have the nonce in them (or the second param?)
- [ ] Refreshing the page does not result in an SSO error

Look at https://github.com/edhemphill/passport-discourse for ideas

**Comment by marcondag** [comment]
Resolved by https://github.com/debtcollective/dispute-tools/pull/40
