### ISSUE TITLE
Logging out on dispute-tools does not log out of discourse

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#146]
Reproduce:

1. Log into dispute tools
2. Log out of dispute tools
3. Open discourse. You are still logged in.

## Acceptance criteria

- [ ] When logging out of discourse, one is logged out of dispute tools
- [ ] When logging out of dispute tools, one is logged out of discourse

## Thoughts and hints

Does discourse have a log out web hook?

**Comment by marcondag** [comment]
Resolved be https://github.com/debtcollective/dispute-tools/pull/40
