### ISSUE TITLE
Improve test coverage of the dispute information forms (technical debt)

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#148]
We have recently found two bugs in the dispute information forms: 
https://github.com/debtcollective/parent/issues/112
https://github.com/debtcollective/parent/issues/147

There are probably more. (there was! https://github.com/debtcollective/parent/issues/176) These bugs have been sneaking in because we don't have any test coverage.

## Acceptance criteria
- [ ] reasonable test coverage of src/javascripts/components/disputes/Information*
Suggested test frameworks: qunit or selenium?

**Comment by marcondag** [comment]
Those controllers would need to be heavily refactored to be unit testable. As it stands they're so coupled to the DOM actually existing. For that reason it's probably most beneficial to do some form of automated regression testing that just controls a browser and walks through filling out the form. I guess qunit does that? Selenium is for more widely used, however. There's even a really good python implementation of it if you want to dabble in that, @shoshber.

**Comment by shoshber** [comment]
Yeah, after our conversation I did some more reading about qunit vs selenium and selenium definitely looks like the best choice! I agree, regression testing is the way to go, now, perhaps with an eye toward refactoring/unit testing in the future (if we ever have time!)
