### ISSUE TITLE
Improve Discourse signup form 

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#152]
Right now is hard to use the signup form, this is due how the fields are shown.

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/89f6e72d-61a2-40e7-b717-9b7849e7fc36)

* We don't have a section for the collectives
* Is not clear what debt amount is
* Solidarity fields labels don't take the parent's container full width

## Acceptance criteria

- [ ] Needs to be more usable, take the current debtcollective.org tools signup form.
- [ ] Labels should to render correctly

**Comment by shoshber** [comment]
Have you seen (this PR)[https://github.com/debtcollective/new-user-plugin/pull/4] which addresses (this issue)[https://github.com/debtcollective/parent/issues/134]?

**Comment by marcondag** [comment]
@orlando I think @shoshber already addressed this. Can you check out that PR she links above and close this issue if it's already addressed? Otherwise the AC need to be updated to reflect what you still feel is missing.

**Comment by orlando** [comment]
this is invalid, we are requesting this data in a wizard now
