### ISSUE TITLE
Update Media Page header and footer links to point to the right places across our services

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#155]
The right text is there for all of them, but we need to update need them to point to the right places within discourse and the tools. 

# Acceptance Criteria
- [x] Make stuff configurable
- [x] Header links
  - [x] Collectives
    - [x] ~Hide if not logged in~ (https://github.com/debtcollective/parent/issues/162)
  - [x] Campaigns
  - [x] Events
- [x] Footer links
  - [x] Collectives (see above)
  - [x] Campaigns (two) (see above)
  - [x] Events
  - [x] Debt Map (hide for now)
  - [x] Dispute Your Debt
  - [x] ~Donate~ (https://github.com/debtcollective/parent/issues/161)

**Comment by shoshber** [comment]
Two questions:

1. Shouldn't we use `dc-vue-header` for the header?

2. For the "Collectives" link, we have two few options:
  a. Link to the regular discourse categories list. Downside: Includes categories like "Site Feedback", which is not technically a collective. Also, if you aren't logged in, you won't actually see any collectives. If you are logged in, you will only see the collectives you are a part of. Upside: no development time
  b. Make a "collectives" page (possibly ganking it from the old site)

3. Where should "debt map" link to?

**Comment by marcondag** [comment]
1. Is there a way to link to a search that shows just the collectives? And we could make this hidden when you're not logged in maybe?
2. I think we can comment that link out for now but it would eventually point to what @orlando was working on

**Comment by shoshber** [comment]
> Is there a way to link to a search that shows just the collectives?

Probably--I have to check to make sure

>  we could make this hidden when you're not logged in maybe?

:+1: 

> I think we can comment that link out for now but it would eventually point to what @orlando was working on

:+1:

**Comment by shoshber** [comment]
> Is there a way to link to a search that shows just the collectives?

I can link to a page that shows topics that are in the collectives, but I couldn't find a way to list just categories. I'm going to quickly write a plugin that adds a page `/collectives` that lists collective categories. I will need to do something similar for the "Campaigns" link anyway. I don't expect it to be difficult.

**Comment by shoshber** [comment]
@marcondag What did you do to the "donate" functionality on the old dispute tools?

**Comment by marcondag** [comment]
It's still there. Any link with the `.js-donate` class gets an on click event listener in `Common.js:L50`
