### ISSUE TITLE
Use user avatar in the header profile dropdown

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#165]
The dropdown image in the header needs to be updated to use the logged in user's Discourse avatar.

**Comment by shoshber** [comment]
Can you add some more detail/a picture? I'm not 100% sure what needs to be done.

**Comment by marcondag** [comment]
If you take a look at the mock ups, the circle for the profile dropdown with your notifications in it is supposed to have your profile picture as the image if you have set one in Discourse. It should be retrievable from the user response that gets stored in the current user prop on the window that the header uses to get all the rest of the information.

**Comment by shoshber** [comment]
You mean like at the top of this mobile mockup?

![mobile 2](https://user-images.githubusercontent.com/1402948/43359505-23956d78-9271-11e8-817d-47b07ca13c00.png)

**Comment by marcondag** [comment]
Yup! There's another mockup with an actual profile picture somewhere.




On Sat, Jul 28, 2018 at 11:19 AM -0700, "Shoshana Berleant" <notifications@github.com> wrote:












You mean like at the top of this mobile mockup?
