### ISSUE TITLE
Wage Garnishment Dispute Small Fixes (from user testing)

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#169]
**Problem 1**

**User comment:** "I typed in 80000000 for wages (it doesn’t let me type commas, nor does it let me put a ‘$’ in front) and then I tried the up and down widget at the right of the box.  Going down changed it to 79999999.99." 

**Solution:** 1) Limit the total amount to no more than six digits. 2) Allow users to insert commas. I don't think dollar signs are necessary however. 

**Problem 2** 

User comment: "I got down to the privacy release I said ‘no’, and then it popped up and asked me 'Are you sure you don’t want to authorize the Debt Collective to advocate directly on your behalf?'And my choices were Yes or No, which gave me pause.  I think it should say ‘Yes, authorize’ and ‘No, don’t authorize’ (and you would have to switch the semantics of the answer from what it is now)."

**Solution:** Change possible responses to Yes, authorize or No authorize. 

**Problem 3** 

**User comment:**
"On the social security number I typed a random one in with spaces, and then when I clicked on ‘Submit’ at the bottom it told me that the field needed dashes or underscores. Seems unnecessary."

**Solution:** Remove requirement that user use dashes or underscores for the social

**Problem 4**

**User Comment:**
"When I hit submit, the page that it reverted to didn’t provide a strong visual cue that the form had been submitted and that it had worked."

**Solution:** Make the 'form completed successfully' note bigger/more prominent.

## Acceptance criteria

-When the user completes a wage dispute, s/he finds the process of filling in fields easy and able to understand what info is being asked for and how to provide it. When the user is done filing the dispute, s/he can see that the process is complete and there is no more to do.

**Comment by orlando** [comment]
This is fixed, @annlarson you can try it in https://staging.debtsyndicate.org/

**Comment by annlarson** [comment]
thanks!
