### ISSUE TITLE
Members should be able to view their profile information

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#17]
In gitlab by @marcondag on Feb 19, 2018, 15:16

As a debt collective member I want to be able to view my profile information so that I know what the debt collective already knows about me

## Tasks

- [ ] Display user information including extended user fields
- [ ] Only logged in members are able to see other members profile's
- [ ] old URL does not show 404

## Assumptions

1. There is a UI mockup for displaying the user information

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:47

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 16:10

removed ~3521981 label
