### ISSUE TITLE
Make Yellow Text on 'About This Tool' Pages More Readable

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#171]
Users have told us that it can be hard to read the yellow text on the ABOUT THIS TOOL pages. Attached is as a sample from the wage garnishment tool About page. 

Can we make this a darker yellow or otherwise help the text to stand out a bit more?

## Acceptance criteria

Members who use our tools have no problem reading the yellow text on the ABOUT THIS TOOL pages. 
![screen shot 2018-06-29 at 4 53 22 pm](https://user-images.githubusercontent.com/13947808/42115669-da4cd086-7bc1-11e8-9666-1dacfc4e9037.png)

**Comment by orlando** [comment]
This is fixed now

![image](https://user-images.githubusercontent.com/849872/45004244-ab6dba00-afb0-11e8-9ff8-cee4ae481fa2.png)
