### ISSUE TITLE
Using a date picker plugin for date inputs

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#173]
Right now we are not using a plugin for date pickers. Date fields are not standard yet and their behaviour changes across browsers, not to mention that their usability is really bad.

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/4acb47d4-a2f2-49f6-b175-226cf9135e75)

## Acceptance criteria

- [x] Research date picker libraries and pick one we can use for the forms: flatpickr
- [x] Implement date pickers in the Dispute form date inputs.

**Comment by shoshber** [comment]
According to `package.json` we are already depending on a library called `flatpickr`, added by @marcondag. I'm not sure if we are actually using it anywhere though. Should we just use this one?

**Comment by marcondag** [comment]
Yes! We used to use it for event creation and even had an implementation using Vue.js to wrap it.




On Fri, Jul 27, 2018 at 8:03 PM -0700, "Shoshana Berleant" <notifications@github.com> wrote:












According to package.json we are already depending on a library called flatpickr, added by @marcondag. I'm not sure if we are actually using it anywhere though. Should we just use this one?

**Comment by shoshber** [comment]
Flatpickr doesn't let me type the date--only click. Does it behave that way for you too? @marcondag
