### ISSUE TITLE
‘dispute-admin’ and ‘admin’ group names are confusing 

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#177]
‘dispute-admin’s (people who deal with the disputes, e.g. Dawn, Thomas) are not necessarily Discourse ‘admin’s. Most will probably be moderators. The nomenclature here has already created confusion and back-and-forth. We should change the name of ‘dispute-admin’ so that there is less confusion.

Suggestions so far (from slack):

* ‘dispute-pro’

This should be done ASAP and should be quick to implement.

### Acceptance Criteria
- [x] changed in the import repo
- [ ] changed in `dispute-tools`
- [ ] (ideally) create a shared constants repo for the org

**Comment by shoshber** [comment]
@orlando when we decide on a new name, should it go in `discourse-seed`?

**Comment by orlando** [comment]
Everything should go in discourse-import, we have a seed file there. We won’t use the other repo anymore

**Comment by shoshber** [comment]
I believe @orlando changed the group name in `dispute-tools`. If so, we can close this ticket.

**Comment by orlando** [comment]
this was implemented
