### ISSUE TITLE
header jumps around

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#178]
![peek 2018-07-27 17-54](https://user-images.githubusercontent.com/1402948/43351398-383cf9cc-91c6-11e8-8582-5382c5ca60ec.gif)

![headerwrongplace](https://user-images.githubusercontent.com/1402948/44553608-fc052d80-a6fb-11e8-945e-66241f38d35d.png)

**Comment by marcondag** [comment]
Is this only happening while you resize the window?

**Comment by shoshber** [comment]
no, sometimes the header is on the wrong location when the window is at certain widths. Sorry, that gif is not very good. I added a screenshot that should be clearer.

**Comment by marcondag** [comment]
Gotcha. I think we need a better strategy for deciding what items get show in the header and in the "more" dropdown... if it is wrapping then it might be better to punt the right most items into the more dropdown until it stops wrapping. But this would be some relatively complex logic... We could also allow you to configure the breakpoints for each item in the configuration object for the header, but that is probably just as complicated. 🤔 What do you think Shoshana?

**Comment by shoshber** [comment]
This kind of design stuff is not my strong point & I haven't looked too closely at how the header is implemented, so I don't have any strong opinions, except that this seems like it must be a common requirement, so there must be some standard ways to handle it.

**Comment by marcondag** [comment]
Yeah... my experience so far has been with just explicitly limiting the number of items in the header or specifying the list for specific breakpoints (that would probably be the easiest).

So maybe a good proposal for a solution would be to add a `minBreakpoint` property to the link configuration object and then for all breakpoints less than that to have the link in the dropdown?

**Comment by shoshber** [comment]
I got a better demonstration:

![headerissue](https://user-images.githubusercontent.com/1402948/46575857-bb036880-c98b-11e8-901b-a01e1e811974.png)
