### ISSUE TITLE
Emoticons don't display in notification tray in dispute tools

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#179]
![screenshot from 2018-07-29 13-44-36](https://user-images.githubusercontent.com/1402948/43369104-13f193fe-9336-11e8-9bd4-61ae7430c8cc.png)

If this is only my computer/browser's fault and y'all can see the emoticons, we can close this.

**Comment by marcondag** [comment]
Oh! I'm assuming Discourse doesn't actually store emojis as unicode and instead uses the `::` syntax and transforms it on load... Not sure how we should handle this. I wonder if there's a library that will transform these automatically? Or else if we could find the map of `key -> emoji` inside of Discourse we could copy that over to the header and make sure it does the transformation on the message body.
