### ISSUE TITLE
Update image references in Power Report

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#185]
All image references to images stored in the `_uploads` collection need to be updated:

<img width="469" alt="screen shot 2018-08-21 at 2 21 29 pm" src="https://user-images.githubusercontent.com/24264157/44475270-6c6f5a00-a5e9-11e8-856f-abecc3a159c8.png">

The above images (which you cannot see because they are incorrectly referenced) are currently sourced as `/image_name.jpg`. This needs to be updated to be `/uploads/image_name.jpg`. 

This will not be a recurring issue and is just a result of dealing with a workaround for a Siteleaf bug where images will not insert correctly in the editor if the image path is on the root of the site.

**Comment by orlando** [comment]
Fixed on https://github.com/debtcollective/powerreport.debtcollective.org/commit/d3cce2d48c16369fa865edddd11b2dcf19c92e8d
