### ISSUE TITLE
Mobile header menu button is a different size when open causing the header to jiggle when toggled between the two states

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#188]
This should be fixed by making the hamburger menu icon smaller to match the size of the `X`. In any case, there should be no horizontal movement in the header when toggling between the two states (nor should the login button be cut off the side of the screen)

<img width="349" alt="screen shot 2018-08-21 at 2 16 18 pm" src="https://user-images.githubusercontent.com/24264157/44475662-7e9dc800-a5ea-11e8-9b81-101fce791eec.png">

<img width="366" alt="screen shot 2018-08-21 at 2 16 14 pm" src="https://user-images.githubusercontent.com/24264157/44475672-80678b80-a5ea-11e8-9fde-f698a2f6b2a0.png">

**Comment by orlando** [comment]
merging with #256
