### ISSUE TITLE
Customizations to the Discourse (Community) Badging system

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#193]
We would like to customize the badging system on Discourse. 

https://staging.community.debtsyndicate.org/admin/badges

We would like badges ONLY in the following areas. The rest can be removed/disabled. 

**New badges**

1) Disputing
Hero Disputer
This would be for anyone who completed a debt dispute

2) Organizing
Hero Organizer 
This would be for people who conduct organizing on the platform, for actual organizing work like creating an event or action.

3) Admin
Admin
This would be a badge for people doing admin work on the platform. It could help users know who the admins are.

4) Solidarity Bloc
Solidarity
This is a badge for people who offer a skill or donate something or in some way perform an act of solidarity.

These can be awarded manually for now.

**Discourse badges**

5) Great Reply
This is so we can encourage people to be nice and encouraging

6) Great Post
This is so we can encourage people to post good stuff. 

This are awarded automatically based on the number of likes a Post/Reply receives.

## Tasks
- [x] Disable all the default badges except for **Great Reply** and **Great Post**
- [x] Create the new badges

## Acceptance Criteria

- Only the badges described above are enabled

**Comment by annlarson** [comment]
Thanks!!!

**Comment by orlando** [comment]
This is implemented on production. We will leave the automatization part here https://github.com/debtcollective/parent/issues/255
