### ISSUE TITLE
Dispute communication with user should be in just one Discourse private message

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#194]
Right now each notification the Dispute tools backend creates a new private message in the Discourse, this causes confusion to both admins and users.

Admins would like to keep the messaging in the Dispute tools backend just for them and move the user notifications to Discourse. 

To organize better the user communication, we will create just one private message in the Discourse per Dispute. This message will be created after **the user starts a dispute filling**

The title for the private message is the following one (https://github.com/debtcollective/parent/issues/201#issuecomment-418200026)

> Dispute ID - Full name - Dispute type

Example:

> 023 - Tim Jones - Tax Offset Dispute

The body of the message will be:

> This private message thread is the best way to communicate with the Debt Collective organizers about your dispute. Check back here for communications from the admin assigned to your dispute or send messages here to contact the administrators.

The message will be between the `dispute_coordinator` group and the User.

## Spec

https://gist.github.com/marcondag/8a04fdee75732493857c6a7d5abf45da

## Tasks

- [ ] Create PM in Discourse after the user creates a Dispute and store the reference.

## Acceptance criteria

- There's one PM per Dispute in Discourse
- The PM is created after the user creates the Dispute.
- The private message title and body follow templates.
- The message mentions the `dispute_coordinator` group.
- There's a link to the PM in the "Edit Dispute Status" view that opens in a new tab.

**Comment by marcondag** [comment]
Can I get some clarification on the requirement for this item? Not sure I understand what the goal is here or even what is supposed to happen.
> Remove notifications when an admin edits a dispute

**Comment by orlando** [comment]
Community thread == PM in Discourse between users an admins.

We can have the thread between the assigned admins and the person that writes the message, if we can disable easily the former is better, from the talk with Dawn they don’t want to notify all the admins in each message. 

Also, not sure if we can send the author as a parameter through the api, so messages come with the real author instead of “system”

**Comment by orlando** [comment]
Oh and about the notifications edit notifications, I think we are sending these when an admin edits the content of the form, if this is correct we need to disable that.

Most of the edits are just typos, per Dawn feedback they only want to notify when is needed

**Comment by annlarson** [comment]
"Admins would like to keep the messaging in the Dispute tools backend and keep the community thread just for user notifications."

I am not sure I understand this or if it is the right instruction. Dawn said the communication in the tools backend is very limited and she likes all the features with Discourse. We are just getting a LOT of messages flying back and forth and trying to figure out how to streamline it. Maybe we need to talk about this once more before a change is made.

**Comment by annlarson** [comment]
cool

**Comment by marcondag** [comment]
Okay. This sounds good. I'm going to split removing the admin form edit notification into a separate ticket as it's just deleting code, so I don't think it needs a spec, and I don't want that work to be blocked while we hash out what the goal is for this ticket.

**Comment by marcondag** [comment]
Is it still a requirement to not send the notification from the `system` user and instead send it from the admins?

Also what should the body of each notification message look like?

**Comment by marcondag** [comment]
Added the spec here: https://gist.github.com/marcondag/8a04fdee75732493857c6a7d5abf45da

I'll update it once I know the answers to the above questions

**Comment by marcondag** [comment]
The ticket explicitly says that the admins want to keep dispute communications in the tools. That’s changed? I’m not sure that actually changes anything about the spec I’ve layed out. Have you read through it?

**Comment by orlando** [comment]
@marcondag Yes, your spec looks good. I talked a couple of days ago and want to discuss it with devs in the dev call. I'll update the ticket after the call.
