### ISSUE TITLE
Changes to "Admin Disputes by name" report

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#196]
This is the link of the report https://metabase.debtcollective.org/question/52

We want to add the following fields to it

- Debt Type
- Debt Amount
- Admin(s) assigned
- Location
- Phone Number

## Tasks

- [ ] Add fields described above to the report

## Acceptance Criteria

- Report should contains the fields described above for each Dispute,

**Comment by orlando** [comment]
Moved from https://gitlab.com/debtcollective/debtcollective/issues/338

**Comment by dawn3296** [comment]
Hi Orlando.
Can this be the layout for the update. Is it possible to put the cells in this order? That will save me time from having to rearrange the columns.

![image](https://user-images.githubusercontent.com/42922071/48876704-30ed5300-edc5-11e8-967a-251fe2ec6fb0.png)

**Comment by orlando** [comment]
@dawn3296 I updated the question on metabase, here's the link https://metabase.debtcollective.org/question/52. Let me know

Thanks!
