### ISSUE TITLE
DC Header grouped notification count is not properly centered

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#199]
<img width="532" alt="screen shot 2018-09-03 at 11 09 27 am" src="https://user-images.githubusercontent.com/24264157/44998384-0a5c1080-af6a-11e8-8ab0-b78cdb7263f8.png">

Browser: Chrome
Subdomain: tools

### Acceptance Criteria

- [ ] The count of notifications is vertically centered in the bubble

**Comment by orlando** [comment]
merged with #256
