### ISSUE TITLE
Members should be able to edit their profile information from the discourse account management

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#20]
In gitlab by @marcondag on Feb 19, 2018, 15:27

As a TDC member I want to manage my account in the same place so that I don't have to manage my account in multiple places

## Acceptance Criteria

- [ ] Users should be able to change any of the extra member fields (#6) in discourse's 
- [ ] old URL does not show 404

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:10

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:47

changed the description

**Comment by shoshber** [comment]
We should also consider disabling the preferences for "watched" and "tracked" categories, since we are reusing that functionality for the collectives
