### ISSUE TITLE
When a User replies in a Dispute PM, it updates the status of a Dispute in the back office

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#206]
We are moving user communication about disputes to Discourse. In order for admins to know there are new user messages, we need a way to display this information in the back office.

The idea is to replace the "User update" status for a "New messages" one. The "New messages" status will be assigned when a **user** writes a message in the Dispute PM in Discourse, messages from **admins** won't change the status.

![image](https://user-images.githubusercontent.com/849872/45003928-3c429680-afad-11e8-8044-2af49f8a539d.png)

The status will then be changed by an **admin** after reading the message, which is part of the workflow at the moment.

## Notes

A possible solution is to create a plugin that makes a request to a private endpoint in the Dispute tools after creating a comment inside a Dispute PM, to change the status of the Dispute in the tools app. 

We need a way to know which PM is a Dispute PM (using custom fields), and a way to access update the dispute status via the tools API. The authentication for the tools endpoint can be a basic `api_token` since this is a system call.

## Tasks

- [ ] Research and spec out the solution, consider edge scenarios.
- [ ] Implement your spec as a Discourse plugin

## Acceptance criteria

- After a **user** comments in a Dispute PM, the status of the dispute is changed to "New messages"

**Comment by orlando** [comment]
This is important, but yeah not a blocker. But we do need to implement this as soon as we have time. For the release most of the fixes/features we need to do are around user communication, and this is a feature that is important for the admins (they filter for new activity messages as part of their workflow)

**Comment by dawn3296** [comment]
I have concerns about this. Can you please let me talk to ANN and come back to this. Can we pause on this.

**Comment by orlando** [comment]
@dawn3296 sure, if you later decide we don’t need it, we can close this ticket.

**Comment by orlando** [comment]
We will change how we do messages in the new release, so this ticket doesn't apply anymore. Closing
