### ISSUE TITLE
Remove all email notifications in the tools app and replace them with Discourse PMs

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#207]
Currently, the tools app send emails after creating a Dispute.

![image](https://user-images.githubusercontent.com/849872/45004117-4e253900-afaf-11e8-9605-af523fb1ae07.png)

They may be other cases where this happens, and we need to replace these with Discourse PMs, appended to the Dispute unique PM (#194)

## Tasks

- [ ] Research and spec out your solution
- [ ] Find all the cases where we send emails and replace these calls with Discourse PMs

### Copy

**Dispute completed**

[link]

If you opted to mail the dispute yourself, it is a good idea to send it certified mail so you can be sure it was received. If you need help mailing it, we will send you the tracking info once it is sent.

Keep in touch with us! It's easy on the platform to send admins a message or photos of responses you receive from your collector(s). And we love to hear, of course, when the debt is discharged or removed from your credit. When you win, we all win.

Love,
TDC

P.s. You can also post any news you receive from the collector on the community pages. The more information we have about how collectors are responding to these disputes the better we can catch those who are breaking the law and organize together for debt relief

## Acceptance criteria

- Instead of users receiving emails directly from the dispute tools app, they should receive PMs in Discourse with the same information (request copy if needed)

**Comment by dawn3296** [comment]
Thank you for disputing your debt! You can download a copy of your dispute here:

[link]

If you opted to mail the dispute yourself, it is a good idea to send it certified mail so you can be sure it was received. If you need help mailing it, we will send you the tracking info once it is sent.

Keep in touch with us! It's easy on the platform to send an admin messages or photos of responses you receive from your collectors. And we love to hear, of course, when the debt is discharged or removed from your credit. When you win, we all win.
Love,
TDC

P.s. You can also post any news you receive from the collector on the community pages. The more information we have about how collectors are responding to these disputes the better we can catch those who are breaking the law and organize together for debt relief

**Comment by marcondag** [comment]
Awesome! Thanks, Dawn!

**Comment by annlarson** [comment]
Thanks Dawn!

**Comment by annlarson** [comment]
The contact form should be something that anyone, member or not, can use. In that case, maybe we have it go to discourse for members and to admin@debtcollective.org for non-members? Or maybe it's easier to just easier to always send a copy to both discourse and to admin@debtcollective so that we are sure to get it. What do you think @orlando ?

**Comment by orlando** [comment]
Let’s just change the recipient of the email to admin@debtcollective.org for now and plan how to integrate this to discourse after launch. I’ll change the description to just include Dispute emails

**Comment by annlarson** [comment]
Sounds good! Thanks.
