### ISSUE TITLE
Move authenticated links logic to handled by the Header

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#210]
Right now we are handling which links should be shown given the session in the tools (by checking the `user.admin` flag). The header has already the functionality to handle this, and works by passing a `roles:['required_role']` attribute to the links configuration

```
var headerLinks = [
      { text: 'Admin', href: '/admin/disputes', roles: [!{JSON.stringify(adminRole)}] },
];
```
We will leave the session in the tools as a way to update the user data when the user tries to access an authenticated route.

## Tasks

- [ ] Move the authenticated links logic to the header
- [ ] Check that admins and users can enter authenticated routes without issues

## Acceptance criteria

- If the users logouts, it will kill both the session in Discourse and the service that is using the Header (ex: dispute-tools)
- Admins and users can use authenticated routes
- User information in the tools database is updated when the user goes to an authenticated route and has no session.

**Comment by marcondag** [comment]
Why do the tools need this?

**Comment by orlando** [comment]
because the tools handle their own session

**Comment by shoshber** [comment]
Let me see if I understand this right with an example:. 

1. User logs in on discourse.
1. User enters tools site. They are automatically logged in.
1. User logs out of tools site.
1. User is still logged in to discourse.

Is that what you mean, @orlando ?

**Comment by marcondag** [comment]
Yes, except the "automatic" logging in will only happen after they have hit an authenticated route. Which is why we let the header handle whether to show authenticated links, so that the tools do _not_ have to log you in. Otherwise how will the admins be able to get an authenticated session in the tools?

**Comment by shoshber** [comment]
Thanks for explaining that user experience so clearly.

**Comment by orlando** [comment]
So after discussing with @marcondag, we can solve this by changing the logic in `header.pug` to have a `roles` attribute for every link we define, and the header will use [filterLinks](https://github.com/debtcollective/dc-vue-header/blob/master/src/utils/filterLinks.js) to only the ones that the user has access (based on the roles the user has in Discourse).

We will still keep the session in the tools, but only for updating user data since it will go through the SSO flow when the user tries to access an authenticated route.

**Comment by marcondag** [comment]
```{ text: 'Admin', href: '/admin/disputes', roles: ['dispute_pro'] }

{ text: 'My Disputes', href: '/disputes/my/', roles: ['trust_level_0'] ```
