### ISSUE TITLE
Add Dispute tools' Redis dependency to the Terraform configuration

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#211]
After merging https://github.com/debtcollective/dispute-tools/pull/61, we will need a Redis instance to store sessions. This needs to be added to the Terraform files and be deployed and tests.

I don't think we need heavy persistency for this, so to keep it low cost, we may use a container in the same machine that runs the Dispute tools to run Redis.

## Tasks

- [ ] Add Redis to the Dispute Tools module
- [ ] Deploy to ECS and make sure it's working

## Acceptance Criteria

- Dispute tools app works after being deploy with Terraform

**Comment by marcondag** [comment]
Is the only thing left for this ticket the second task, deploy and verify?

**Comment by orlando** [comment]
@marcondag I deployed on Monday but it was failing when creating the session, so I rolled back the deploy. I’ll debug that and close this asap.
