### ISSUE TITLE
Migrate Dispute comments to the Dispute PM in Discourse

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#215]
Right now we are not migrating Dispute comments from the old platform to the new one, we don't want to lose these conversations and these should be saved as part of the migration.

## Tasks

- [ ] Create a Discourse PM for every Dispute
- [ ] Import all the comments between organizers and admins, admin notes shouldn't be added.

## Acceptance criteria

- All comments in a Dispute should be added to the their respective PM in Discourse

**Comment by marcondag** [comment]
Should we add to this ticket to also add assigned admins to the dispute thread?

**Comment by orlando** [comment]
I think we can skip that. Most of these are not going to be used and I want admins to get used to the system first before having too much in their inbox.
