### ISSUE TITLE
Copy changes for the Power Report

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#218]
We have a few sections in the Power Report that need copy changes, these are:

- [Profiles](https://manage.siteleaf.com/sites/5af700ee6246c948264f6bf4/collections/profiles)
- [Letters](https://manage.siteleaf.com/sites/5af700ee6246c948264f6bf4/collections/letters)
- [News Analysis](https://manage.siteleaf.com/sites/5af700ee6246c948264f6bf4/collections/news_analysis)

Specifically we need to add a sub-title for each of the pages inside the categories listed in the ticket as well as for any posts and statements that can. This helps make the home-page especially look more fleshed out and content rich.

Right now they have a test copy used for development, but we need these to be reviewed/approved by @annlarson.

## Tasks

- [ ] Create copy for the sections listed above

## Acceptance criteria

- We have the copy for each of these sections updated in Siteleaf

**Comment by marcondag** [comment]
Specifically we need to add a `sub-title` for each of the pages inside the categories listed in the ticket as well as for any posts and statements that can. This helps make the home-page especially look more fleshed out and content rich.

**Comment by orlando** [comment]
@marcondag cool, adding that comment to description

**Comment by marcondag** [comment]
@annlarson These pages still need to have sub-titles added:

http://powerreport.debtsyndicate.org/reports/abolishfinesfees/

**Comment by annlarson** [comment]
Done
