### ISSUE TITLE
Create debtcollective Bootstrap theme

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#22]
Designs here https://www.figma.com/file/fC59BoZRp0axEVCXexnJkbnj/DC_Design_System_MASTER

## Acceptance Criteria

- [ ] Profile service should implement designs
- [ ] old urls do not show 404s

## Assumptions

- We have designs approved

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 11:46

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 16:10

removed ~3521981 label

**Comment by orlando** [comment]
Implemented here https://github.com/debtcollective/ds-bootstrap
