### ISSUE TITLE
Adding artists statement to power report

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#223]
The following text is a statement from the artist that should replace the text that is currently under her drawing on this page: http://powerreport.debtsyndicate.org/artwork/public-bank/

**Statement by the Artist**

If the status quo is not challenged by the masses, what is considered possible will remain defined by those in power. I believe organizing around debt is an important and necessary part of transforming the current power structure; by putting that power back in the hands of THE PEOPLE to decide what is possible, what is needed and what is acceptable. 

We live in a time with no real representation and mounting deregulation; our tax dollars largely go to the military industrial complex, tax incentives for fossil fuel extraction and the privatization and sale of public spaces. The corporate welfare state is continuing to balloon with endless mega tax breaks for the super rich on the backs of the underserved. Through collective action we can force the hand of the oppressors (or 1%, or oligarchs?) and flip the paradigm. In reality the employer/ corporation/ government needs the worker, the tax payer, not the other way around and in realizing that, we find where the collective power resides. 

For me painting is an important tool that seeks to hold the afflicted in love and testimony and shows those of privilege and power their own culpability big or small by addressing the problems of our uncivilized society of so called progress.

This painting for the Debt Collective (yet to be named) is an epic that lays out multiple and intersectional forms of egregious abuse. The intention of this work is to expose economists, corporations, paid politicians, lobbyists, international special interest groups, lenders, traders, debt collectors and human relics from the history of global neoliberal capitalism living and dead and then literally surround them with prime examples of the economically oppressive and ultimately enslaving institutions that they personally profit from. The water is rising along with the indelibleness of the repercussions of their policies. We get a sense of what will and might happen if we are left to their callous neglect. Encapsulating the whole of the painting are various forms of protest, collective action, strike, dissent and struggle. 

The people are rising too, they are not afraid anymore because they have nothing to loose.

-- Haley Hughes

**Comment by marcondag** [comment]
@annlarson Rightfully pointed out that she can do the text change inside of siteleaf 🙂
