### ISSUE TITLE
Artist statement for Phil Ashworth

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#225]
The following is an artist statement that should replace the text that is currently located here:
http://powerreport.debtsyndicate.org/artwork/dystopia-comic/

An Interview with the artist

**Why are we all in so much debt?**
I feel like it has a lot to do with the selling of the American dream to the consumer. A lot of people are told when they're growing up that if you go to college and get a good education and work really hard you can have this and that and I think a lot of people bought that idea.

**Are we living in neo-feudalist times? What even is that?**
Between the division in our classes where each side is blaming each other for our problems rather than the people running the show at the very top, the vanishing middle class, the longer hours at work with pay that does not reflect the cost of living and fewer benefits it does feel like we are entering a neo-feudalist society. Neo-feudalism is categorized as a system where the wealthy have more control than any other social class and possess the majority of the wealth while the poor are subjected to unequal rights and have very little opportunity for economic growth.

**If a 7-year old were to ask you what was happening in this comic what would you tell them?** 
Ooh, that's a tough one. I wish I knew a 7-year old that I could run this by and see if they just look bored, confused or maybe shake their head a little like it makes sense. But, I think I would say something like, It's about this large group of people in a bizarre futuristic world who are under total control by these evil guys who are sucking up everything and keeping it all for themselves. Eventually the people get so upset about the way they're being treated that they band together and take down these evil people that rule over them so that they can all enjoy the things they once had.

-Phil

**Comment by marcondag** [comment]
@annlarson Rightfully pointed out that she can do the text change inside of siteleaf 🙂
