### ISSUE TITLE
Remove drop down menu from power report

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#226]
This menu should be removed or disabled until we have something to put there. 
![more 1 2 3_1](https://user-images.githubusercontent.com/13947808/46543915-210ac580-c890-11e8-8bfd-4b252958c9a9.jpg)

**Comment by marcondag** [comment]
Done.

If this doesn't update in a timely manner for other folks we should do a root cache invalidation on Monday before we launch.
