### ISSUE TITLE
Changes to Dispute Statuses

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#251]
We want to introduce changes to the Dispute statuses, to help admins with their workflow. These will be the list of statuses we want to have

| Name  | Assigned by | Description |
|---|---|---|
| New |   System   | New disputes with no details filled | 
| Incomplete |   System   | When the dispute has been edited | 
| Complete  |   System   | When the dispute has been filled completely |
| User update  |   System   | When a user replies in a Dispute PM, #206 |
| In review  |   Admin   | |
| Contact admin   |   Admin   | |
| User to mail   |   Admin   | |
| Documents sent |   Admin   | |
| 2nd dispute |   Admin   | |
| Discharged |   Admin   | |
| Resolved |   Admin   | |
| Cold case  |   Admin   | |
| Research needed |   Admin   | |
| Active legal |   Admin   | |

We also want to defer the Dispute thread in Discourse till the status changes to **Incomplete**, right now admins are getting too much noise from Disputes that are created and left there.

## Tasks

- [ ] Implement the statuses above
- [ ] Create Dispute thread in Discourse when the status reaches **Incomplete**

## Acceptance criteria

- Admin should see the dispute statuses listed above to be assigned in the tools backend
- Dispute thread creating should happen after the user fills some details in the Dispute
- System statuses should be assigned as described above

**Comment by dawn3296** [comment]
looks good.

**Comment by dawn3296** [comment]
Is there a different ticket for the status message?

**Comment by orlando** [comment]
@dawn3296 this ticket is just to introduce the "New" status and the dispute thread creation, the messages will be tackled in another ticket
