### ISSUE TITLE
Improve Dispute Tools installation documentation

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#254]
The installation documentation is missing some details on how to setup the integration with Discourse. We want to make this information clear so others developers can setup their envs quickly.

## Tasks

- [ ] Add details on how to integrate Discourse with Dispute Tools app
- [ ] Rewrite the installation section in the README to have all the details

## Acceptance criteria

- Installation documentation show be clear on how to configure Discourse and the rest of the services

**Comment by duranmla** [comment]
Make sure to check https://github.com/debtcollective/dispute-tools/pull/93
