### ISSUE TITLE
Update Text on About This Dispute for Credit Report Dispute

### ISSUE THREAD

**Issue by annlarson** [debtcollective/parent#258]
The text on the About this Dispute page reads like this:

Millions of us have errors on our credit reports, which makes it harder to do basic things like get a job or rent an apartment. Fight back! You can get a free copy of your credit report once per year at annualcreditreport.com or call 1-877- 322-8228. For a list of common errors to look for, go here. Once you have determined that there are errors on your report, you can use this tool to ask for a correction. This tool will help you write a dispute letter to the three main credit reporting agencies. The Debt Collective will submit the letters your behalf. For more information about the process, go here. Please have a photo of your picture ID ready to upload (taking a picture with your camera phone is fine).
____

It should be changed to read like this:

Millions of us have errors on our credit reports, which makes it harder to do basic things like get a job or rent an apartment. Fight back! You can get a free copy of your credit report once per year at annualcreditreport.com or call 1-877- 322-8228. If you do not have a social security number, you cannot use this service online. The Debt Collective is working on convincing annualcreditreport.com to address this problem. For now, to access your report, please send a letter with the following information: 

-Your full name
-Your date of birth
-Your current mailing address
-Your previous mailing address (if you have lived at your current address for less than 2 years)
-State which credit reporting agencies (Equifax, Experian, TransUnion) you want a report from. 

Send the request to:

Annual Credit Report Service
PO BOX 105281
Atlanta, GA 30348-5281

Once you receive your report, you can use this tool to dispute errors. For a list of common errors to look for, go here. Once you have determined that there are errors on your report, you can use this tool to ask for a correction. This tool will help you write a dispute letter to the three main credit reporting agencies. The Debt Collective will submit the letters your behalf. For more information about the process, go here. Please have a photo of your picture ID ready to upload (taking a picture with your camera phone is fine).

## Acceptance Criteria

- Credit Report description text should look like described above.

**Comment by dawn3296** [comment]
For now, to access your report, please send a letter with the following information:

-Your full name
-Your Full Name
Your  Individual Taxpayer Identification Number (ITIN)  
-Your date of birth
-Your current mailing address
-Your previous mailing address (if you have lived at your current address for less than 2 years)
-State which credit reporting agencies (Equifax, Experian, TransUnion) you want a report from.
