### ISSUE TITLE
Locations plugin

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#26]
In gitlab by @marcondag on Feb 19, 2018, 15:53

As a TDC member I want to be able to add locations to topics for other members to be able to filter topics by location and be able to participate in local organizing efforts

## Tasks

- [x] Install [`locations-plugin`](https://meta.discourse.org/t/locations-plugin/69742) into discourse  
    This has been handled by @marcondag 's terraform script

## Acceptance Criteria

- [ ] Members should be able to add a location to any topic (any or just events/actions?)  
    This AC will probably have a requirements change down the road, but for now we'll enable it for every category as part of the seeding process.

**Comment by orlando** [comment]
Implemented here https://github.com/debtcollective/discourse-seed/pull/8
