### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when resizing header

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#267]
There's an issue when resizing the viewport in the tools app and the header tries to accommodate items in the dropdown. There's a `Maximum call stack size exceeded` in the console, but the header keeps working correctly.

![image](https://user-images.githubusercontent.com/849872/50659889-9eafa180-0f63-11e9-9fa3-3de88cedec97.png)

## Notes (optional)

This error is happening in the tools app

## Acceptance criteria

- Error shouldn't appear in the console

**Comment by duranmla** [comment]
Check PR at: https://github.com/debtcollective/dc-vue-header/pull/13
