### ISSUE TITLE
Setup Discourse as SSO provider

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#27]
In gitlab by @marcondag on Feb 19, 2018, 16:05

## Acceptance Criteria

- [x] Users should be able to log into the Debt Collective once using their community account and access all the debt collective services using the same discourse account
- [x] users should be redirected to what they were trying to do pre-auth
- [x] This needs to be enabled in the configuration yml file, injected into the Discourse instance by Terraform

## Resources

https://meta.discourse.org/t/using-discourse-as-a-sso-provider/32974

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 16:58

changed milestone to %1

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:25

changed the description

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:26

assigned to @marcondag

**Comment by orlando** [comment]
I'll check how to include this configuration in Discourse

**Comment by marcondag** [comment]
If it's not in the yml then we can also configure it through the API using the discourse seed repo.

**Comment by orlando** [comment]
This is done here https://github.com/debtcollective/ds-terraform/commit/b096d087c46cbb4a8f7b05ef6f96ca79502e345c. We are only adding the `sso_secret` variable since is the only thing we need to inject for now
