### ISSUE TITLE
Sign Up screen does not full display on phones

### ISSUE THREAD

**Issue by dawn3296** [debtcollective/parent#272]
Seen on 3 different mobile devices. All Android platforms. Not sure what browser on the phones.

1. When you access the home page. screen does not show that you need to scroll over to the right to see the "login" button.

2. Signing screen cuts of the first field title 'EMAIL ADDRESS
user gets to bottom and clicks submit. Comes back with an error, and highlights first field. but you cannot see what is it asking for.

![Capture+_2019-07-16-07-49-04](https://user-images.githubusercontent.com/42922071/61324912-556cc400-a7c8-11e9-9d0f-0c99ec28bf0b.png)
![Capture+_2019-07-16-07-49-40](https://user-images.githubusercontent.com/42922071/61324914-556cc400-a7c8-11e9-9288-df69f43e127d.png)

**Comment by dawn3296** [comment]
The circled blue section is all you see from the screen.

![image](https://user-images.githubusercontent.com/42922071/61325111-dc21a100-a7c8-11e9-92d6-a95a195d3783.png)

**Comment by orlando** [comment]
Issue moved to [debtcollective/dispute-tools #186](https://github.com/debtcollective/dispute-tools/issues/186) via [**ZenHub**](https://www.zenhub.com/)
