### ISSUE TITLE
User should join collectives (categories) as part of signup in Discourse

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#28]
In gitlab by @marcondag on Feb 19, 2018, 16:07

As a User, I don't want to see posts of collectives I'm not part of, so it doesn't clutter my feed

## Acceptance Criteria

* When you sign in to Discourse, it will add you to the required users_groups so you have access to collectives.

**Comment by orlando** [comment]
This should be fixed by https://github.com/debtcollective/new-user-plugin/pull/2
