### ISSUE TITLE
Delete all the code not related to DisputeTools

### ISSUE THREAD

**Issue by sarayourfriend** [debtcollective/parent#31]
In gitlab by @marcondag on Feb 19, 2018, 16:42

We need to remove all the code from https://gitlab.com/debtcollective/debtcollective that is not related to Disputes.

## Acceptance Criteria

- [ ] Create a new repository and move the code corresponding to DisputeTools

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:27

changed title from **Delete all the code no{-n-} related to DisputeTools** to **Delete all the code no{+t+} related to DisputeTools**

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 19, 2018, 17:28

assigned to @marcondag

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 23, 2018, 20:29

@marcondag @shoshber Do y'all think I should rip out the user related stuff for this too? Or wait to do that when implementing the discourse SSO?

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 23, 2018, 20:30

I think we can do that and start integrating SSO, you can test against a discourse instance running locally

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 23, 2018, 20:35

Yup. That simplifies this ticket significantly. Don't have to fix stuff that's going to get thrown out anyway :+1:
