### ISSUE TITLE
Install Wordpress instance

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#34]
In gitlab by @zakgreene on Feb 19, 2018, 16:58

## Acceptance Criteria

* [ ]  A blank install of Wordpress is production-ready and available to Steve and Zak

**Comment by orlando** [comment]
I'll leave this ticket blocked until we defined what we are going to do. We can save money by using a static site generator instead of maintaining an RDS instance + EC2 server + ELB

**Comment by orlando** [comment]
This is up at media.debtsyndicate.org
