### ISSUE TITLE
Update Disputes service to use SES instead of Mailgun

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#35]
In gitlab by @marcondag on Feb 19, 2018, 17:00

## Acceptance Criteria

- [ ] Mailgun integration is removed
- [ ] All emails are sent through Amazon SES
- [ ] Verify emails aren't getting caught by spam filters https://gitlab.com/debtcollective/debtcollective/issues/222
 - [ ] Make sure we have DNS configured correctly (https://support.cloudways.com/configure-domain-with-mailgun-spf-and-dkim-records/)

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:51

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:51

changed the description

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:52

mentioned in issue debtcollective#222

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:53

added ~3534065 label

**Comment by marcondag** [comment]
Done for the debtcollective tools @ 9:38AM, Saturday, March 10

**Comment by marcondag** [comment]
Reverted for debt collective tools. The strategy will be to continue using MailGun for `debtcollective.org` emails. We will only use SES for `debtsyndicate.org`. This is to avoid potentially hurting our SES account's rating with the old domain which confused some folks during RJ who thought we were debt collectors and marked us as spam.

**Comment by orlando** [comment]
@marcondag I think we should bring this back

**Comment by orlando** [comment]
Implemented in https://github.com/debtcollective/dispute-tools/pull/6
