### ISSUE TITLE
Implement Media Site Designs into a Jekyll Theme

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#40]
The jekyll theme lives here: https://github.com/debtcollective/jekyll-debtcollective

The designs live here: figma://file/5M23j5DubR2XEnbtB3whdf/DS_Media-Page_designs-(Copy)

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 20, 2018, 13:36

added ~3522303 label

**Comment by orlando** [comment]
This are implemented here https://www.figma.com/file/HM5nuixnJQD31TWqk4wE7ZNt/DS_Media-Page_designs?redirected=1
