### ISSUE TITLE
Style guide/design system

### ISSUE THREAD

**Issue by sarayourfriend** [debtcollective/parent#44]
In gitlab by @stephenkistner on Feb 20, 2018, 09:55

* [x]  Colors
* [x]  Typography
* [x]  Heading/copy sizes
* [x]  Input elements (buttons, form fields)
* [x]  List styling

**Comment by marcondag** [comment]
In gitlab by @stephenkistner on Feb 24, 2018, 11:17

added ~3522297 and removed ~3551412 labels

**Comment by marcondag** [comment]
In gitlab by @stephenkistner on Feb 24, 2018, 11:21

changed the description

**Comment by marcondag** [comment]
In gitlab by @stephenkistner on Feb 24, 2018, 12:11

changed the description
