### ISSUE TITLE
As an admin I want to be able to tell when a user opts to mail dispute herself

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#49]
In gitlab by @shoshber on Feb 21, 2018, 10:46

Currently, we offer users a choice to mail the dispute forms themselves or to have us do it for them.  Dawn (admin) cannot tell when users select to mail themselves. 

## Acceptance criteria

The tools admins should be able to see when a user chooses to mail the form themselves.

from https://gitlab.com/debtcollective/debtcollective/issues/328

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 10:46

mentioned in issue debtcollective#328

**Comment by annlarson** [comment]
Hi, Will this feature be implemented in the next release? Just confirming. Thanks.

**Comment by orlando** [comment]
I think we already implemented this, I’ll confirm once I get to my computer

**Comment by orlando** [comment]
@annlarson yes, this is implemented already

We are showing this in the dispute detail in the admin panel

![image](https://user-images.githubusercontent.com/849872/39893355-15e301fe-5469-11e8-8b0e-0b6745368e84.png)
