### ISSUE TITLE
If a request to save a dispute to S3 fails, the dispute file is lost and there is no easy way to trigger re-render

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#54]
In gitlab by @shoshber on Feb 21, 2018, 11:14

https://gitlab.com/debtcollective/debtcollective/issues/314 (make sure to look at the discussion)

When submitting a dispute form as completed (after selecting whether to mail the documents yourself or have TDC staff do it for you), if the request to save the rendered dispute documents to S3 fails, then the documents are lost, the user sees a confusing 500 error and attempting to download the dispute documents will result in a 404.

## Steps to reproduce

1. Ensure any communication to S3 will fail. The easiest way to do this locally is to disconnect your internet connection while the backend is already running.
2. Fill out a debt dispute (the Private Student Loan tool has a short, simple form)
3. Select whether or not to have to documents for you
4. Click submit

#### Expected results

A user friendly error message responds letting the user know that the dispute documents could not be rendered at this time and to contact an administrator

#### Actual results

A 500 error appears saying amazon was inaccessible.

## Implementation notes

Might be a good idea to add a new dispute status only used in this case for the admin to know that the rendering failed. This status would not be an option available to the admins when they are updating the status themselves and would always have `notify` as true so that the user gets an appropriate email reminding them that the documents were not rendered and to contact an admin.

**Comment by orlando** [comment]
This is an edge case, I don't think a connection to S3 from EC2 will fail. If that happens, we should get a notification from Sentry, and then we can re render the form.

Implementing this will add a lot of complexity for a problem we may never have

**Comment by shoshber** [comment]
Who gets the Sentry notification?

**Comment by marcondag** [comment]
They'll get posted in slack.
