### ISSUE TITLE
Limit re-render retries

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#56]
In gitlab by @shoshber on Feb 21, 2018, 11:22

* Reduce the ease of DDoS attacks--both from attackers and from accidentally DDoS-ing ourselves
* Don't waste resources on rendering attempts that will never work

## Tasks

- [ ] add jitter, exponential backoff https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
- [ ] cap retries at 3 (or 2?)

https://gitlab.com/debtcollective/debtcollective/issues/304
https://gitlab.com/debtcollective/parent/issues/51

**Comment by orlando** [comment]
I don't think we need to worry for this now.
