### ISSUE TITLE
emphasize dispute "save" capability

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#59]
When the user is filling the form, we show a **Save and close** button in the top right corner

![image](https://user-images.githubusercontent.com/849872/38342316-65a93664-3843-11e8-9222-a6c0aa68f7d9.png)

Some options/thoughts: make the button bigger; remove or change the behavior of the 'x' button; move the "save and close" button down to be to the left of "Continue next step," and possibly add a "Cancel" button too.

**Comment by orlando** [comment]
a possible solution is to put both buttons (**Save** and **Cancel**) at the bottom of the form

**Comment by shoshber** [comment]
Does anyone remember what exactly the problem we are trying to solve is?

**Comment by shoshber** [comment]
What if we just auto-save the data?

**Comment by shoshber** [comment]
Solves this problem & way better/modern user experience

**Comment by orlando** [comment]
@shoshber in this case I'm not a fan of that approach, users can make mistakes and may want to keep the form the state it was. We could change the Save & Close for Save and change the X for cancel (or keep it, I don't see how people wouldn't understand that X is for closing)

**Comment by marcondag** [comment]
Orlando and I discussed a possible solution would be to remove the save and close button from that modal and instead put two buttons at the bottom, one labeled something like "Save for later" and the other "Submit for review". "Submit for review" would do what the current button at the bottom of the form does and "Save for later" would do what the save and close button does. 

The difference between the two is that when you "Submit for review" we validate the data and return errors if it is incomplete or incorrect. "Save and close" does _not_ validate the form before saving, allowing the member to complete half the form and leave the rest unfinished. In the latter case it also does not allow the member to move forward with the dispute as it does not count the form as having been "completed".

**Comment by shoshber** [comment]
Moving the 'save' button to the bottom would actually make it less visible
in some cases, right?

**Comment by marcondag** [comment]
Definitely, but it's not an atypical workflow to have the save button at the bottom. On the other hand, we could just get rid of the `X` and leave the save and close button where it is, just change it to be `btn-info-outline` and bigger so that it's more noticeable. And maybe duplicate it on the bottom? But I don't really like having it on the screen twice.

**Comment by shoshber** [comment]
When I was playing around with this, I found that moving the save button to
the bottom of the form was harder to implement than expected (although I
didn't spend much time on it). In the interest of time, I vote for
eliminating the 'X' and enlarging the save button but leaving it where it is

**Comment by marcondag** [comment]
Sounds good to me. Will you also update the text on each of the buttons like we mentioned above?
