### ISSUE TITLE
Create redirects for historical pages

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#60]
In gitlab by @shoshber on Feb 21, 2018, 11:43

redirects from the pre-Tafka debtcollective.org site. We had other pages that produce 404s right now. In case there are links to our old site out there in the web, it’d be good to have a place to direct those users besides 404.

In fact, debtcollective.org/corinthiandtr says "Cannot get /corinthiandtr," not even a 404 page. :/

/corinthiandtr -> the route for DTR disputes
/howfartofree -> a copy of this page https://web.archive.org/web/20160430060203/https://debtcollective.org/howfartofree

https://gitlab.com/debtcollective/debtcollective/issues/189

**Comment by shoshber** [comment]
It depends how many people are using the old URLs. How might we find that out?
