### ISSUE TITLE
Add versioning to dispute template rendering and forms

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#64]
In gitlab by @shoshber on Feb 21, 2018, 14:26

We currently do not have the ability to version the `normalize` functions based on any changes to the forms that might be made and already in the past few months we've had to make breaking changes to the data the forms are collecting.

This means that we right now have to check for the different little pieces of data in the normalize function. It's not a big deal now but it will quickly get out of hand as we make more and more changes to the data the form collects. This will also become a big problem if we need to completely change a section of data that a form collects.

## Implementation notes

- Add a version property to the form data that is saved with the dispute
- Incorporate a function on the `DisputeTemplate` class that is capable of marshaling the form data to the correct normalize function given the form version associated with the dispute.

## Questions

If a dispute needs to have its form data updated after a form configuration is updated, how will we handle that for the front end? Do we keep each and every version of a form's configuration around for the rest of time? Is there some reasonable amount of time after which we may deprecate a form configuration and its normalize function?

## Acceptance criteria

- [ ] Form data from any point in time should be able to be rendered using the same data provided the first time

https://gitlab.com/debtcollective/debtcollective/issues/321

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 14:26

added ~3522123 label

**Comment by orlando** [comment]
I don't think is worth investing time in this, it adds a lot of complexity for a feature we may never use

Closing
