### ISSUE TITLE
Move/maintain admin pages

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#65]
We don't want to lose the functionality when we move campaigns/collectives/events/users to discourse. The disputes index page can remain where it is.

Earlier thoughts/discussion: https://gitlab.com/debtcollective/debtcollective/issues/305

Also: https://gitlab.com/debtcollective/debtcollective/issues/302.

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 14:33

added ~3522123 label

**Comment by orlando** [comment]
We won't move Dispute admin to Discourse, but the rest of the social features will live there.

Closing
