### ISSUE TITLE
Admins are notified when a debt dispute is filed or updated.

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#67]
In gitlab by @shoshber on Feb 21, 2018, 14:42

Admin receives a notification when they log in there is an update to the disputes already on file.

Perhaps only for disputes the admins are assigned to.

Implemented as part of a general-purpose notification system? Integrate with discourse?

https://gitlab.com/debtcollective/debtcollective/issues/255

**Comment by orlando** [comment]
@marcondag not sure if this is implemented, and not sure if we should implement it now. I'll move this to Icebox for now
