### ISSUE TITLE
User Detail Screen for Admins

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#68]
In gitlab by @shoshber on Feb 21, 2018, 14:47

As members join, use our tools, and communicate with each other, it would be great if admins could access a screen that details activities and status of each user.

As an Admin, when I log in through Admin>user>edit User screen, I would like to be able to view all dispute and the status of the disputes. I would also like to be able to click on any of the disputes and be taken to the comment screen to view the comment log for that dispute. (https://gitlab.com/debtcollective/debtcollective/issues/237)

Acceptance Criteria
-------------------

* Name, email, phone #, state, list of disputes submitted and their status,
* A space to add notes on disputes. Some form of back end communication on statues. (adding: reviewed, mailed, etc)

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 14:49

changed the description
