### ISSUE TITLE
Establish roles

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#71]
In gitlab by @shoshber on Feb 21, 2018, 15:14

Currently we have only two roles: "Admin" and "User". It has become clear that that this is too simplistic, and that some users may need more than one role at a time.

## Acceptance criteria
- [x] Discourse treats these roles as user groups
  - [x] `disputes-admin` - Dawn, people who handle disputes
  - [x] `<collective>-moderator` - for moderating the forum related to the collective (https://gitlab.com/debtcollective/debtcollective/issues/227)
  - [x] `<campaign>-moderator` - the same as above, but for campaign tags
  - [x] ~~`community-moderator` - the same as above, but for the entire forum~~ Just use Discourse's built in moderator role
  - [x] ~~`super-admin` - super-powered admin that can do things that affect multiple services, like deleting and banning users~~ Unnecessary; just a regular discourse admin will suffice for this. 
- ~~Discourse displays the roles next to the member handle/name (https://meta.discourse.org/t/how-are-user-titles-generated/57792/3 ??)(https://meta.discourse.org/t/how-can-i-apply-a-badge-to-group-of-users/17998 ??)(https://meta.discourse.org/t/questions-about-moderator-shield-badge/75098/4 ???)~~

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 21:18

Great, I added `community-organizer` to the list

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 21:18

changed the description

**Comment by shoshber** [comment]
Are the "Assumptions" on this ticket fulfilled? Or is this ready for development work?

**Comment by marcondag** [comment]
I think what's there so far is good. We probably won't know more than that until after it's being used. 

I'll remove super admin as that's just a regular discourse admin.

**Comment by shoshber** [comment]
Some questions about the second requirement: "Discourse displays the roles next to the member handle/name"

1. What if someone has more than one role? Is it ok to only display one? (If so, then it's already built into discourse.)
2. Do we want to show the roles next to every post? Or display the roles on the user profile? (Where else might we want to display the roles?)

@annlarson
