### ISSUE TITLE
General category/Where will users view agnostic campaigns?

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#72]
In gitlab by @shoshber on Feb 21, 2018, 15:32

We planned for each collective to be a category (subforum), and members of each collective can only see stuff that's related to their own collective (and launched, public campaigns). This means those members can see campaigns pre-launch that are associated with their collective, and cannot see pre-launch campaigns from other collectives.

However, agnostic campaigns are not associated with any collective (except the "invisible" collective--this idea will probably be dropped in discourse). By the rules set out above, no one would be able to see them!

Solution?: A "General" category that everyone has access to. Agnostic campaigns show up in that category.

Kinda related to https://gitlab.com/debtcollective/debtcollective/issues/224
and 
https://gitlab.com/debtcollective/parent/issues/15

**Comment by orlando** [comment]
The solution for this, is to use tags for all the posts related campaigns. for example `#medical-debt`
