### ISSUE TITLE
As an Admin, I should be able to see the same forms the user filled, so I can edit details if needed

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#74]
In gitlab by @shoshber on Feb 21, 2018, 16:01

In the dispute list in the admin panel, you should be able to see the forms the user filled, so they can fix errors or modify the content of the dispute.

## Acceptance Criteria
* There should be a way to see the same form the user filled in the admin panel
* Admin should be able to change the content of the Dispute forms the user has filled
* Admin should be able to see any attachments the Dispute has

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 16:01

marked this issue as related to debtcollective#216

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 22, 2018, 16:00

changed title from **As an {-admin, see errors of the dispute-}** to **As an {+Admin, I should be able to see the same forms the user filled, so I can edit details if needed+}**

**Comment by marcondag** [comment]
In gitlab by @marcondag on Feb 22, 2018, 16:00

changed the description

**Comment by orlando** [comment]
Duplicated https://github.com/debtcollective/parent/issues/99
