### ISSUE TITLE
Map feature

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#76]
In gitlab by @shoshber on Feb 21, 2018, 16:09

Let's collect ideas/info on the map feature here. It won't be implemented until after the discourse, hub, media page, and wiki services are complete so we have time.

* Having a map of where users are in the collective (along with the list of red squares/pictures) would be really awesome to see to help people feel like there are people around them. (https://gitlab.com/debtcollective/debtcollective/issues/215)

**Comment by orlando** [comment]
We won't be doing this for now, let's create a new ticket when is time to implement this

**Comment by shoshber** [comment]
Isn't that what "Icebox" is for?
