### ISSUE TITLE
Semantic names for generated dispute docs

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#77]
In gitlab by @shoshber on Feb 21, 2018, 16:12

https://gitlab.com/debtcollective/debtcollective/issues/209

A wish would be to have the system generate a file name that can help admin organize files and disputes easier.
as you see in the attached image, the files download as a zipfile as "debt-collective-dispute". It takes extra time to download one file at a time, rename it, etc. 

Having file names by user and dispute tool is important for processing the initial dispute and tracking the files. Specially when they are incomplete and we need more information. Admins are currently make a "case file" for each debtor. 

![file_names](/uploads/091249fa43c66f486b7b1be692fbcff1/file_names.JPG)

## Acceptance Criteria

* The disputes would have a file name that includes the name and dispute type of the user. For the dispute type, we will use the `DisputeTool.readable_name` field in snake_case. For example, if Ann Larson filed a credit report dispute, the file name will be: **ann_larson_credit_report_dispute.zip**

**Comment by orlando** [comment]
@marcondag do we have better names with the new implementation?

**Comment by marcondag** [comment]
Nope, no work has been done on it yet but yeah, it should be fairly simple! You can also just use the slug property on the dispute tool and replace the dashes with underscores. 

This is also just for the zip, right? The documents themselves are already named with the dispute type and a guid.

**Comment by orlando** [comment]
Yes only for the zip files

**Comment by orlando** [comment]
We will need to add more data to users, like names for example. Right now we are storing just an external id, and I won't like to couple more parts of the app to Discourse.

I'll have to rework how our authentication works in order to keep data in the database.

**Comment by marcondag** [comment]
Isn't the point of SSO to store that data in one place? You can easily just request the user's info from Discourse and have anything you need or want to put in the filename. No need to rework anything.

**Comment by orlando** [comment]
that's not entirely correct, SSO takes care of authentication and providing user identity to other apps, these other apps may store user data without problems.

**Comment by shoshber** [comment]
What if a user's details change on discourse? How do the other apps know to update the data?

**Comment by shoshber** [comment]
That's fine. Let's add a note to any user detail editing pages that they may need to log out/log in for details to be updated.

**Comment by marcondag** [comment]
@orlando I'm assuming you never got around to this? I can take this if you like and have a spec done by EOD today.

**Comment by orlando** [comment]
Yeah haven’t got there yet. Instead of working on this one today, what about if you help Shoshana get the fix for the forms?

**Comment by marcondag** [comment]
I mean, I'm pretty sure Shoshana doesn't need my help on it and I can certainly be available for questions. Is there any reason we shouldn't work on this as soon as possible? You've got several other tickets on your plate and the organizers have been asking for this for a while.

**Comment by orlando** [comment]
Yeah this is not blocking for the release and I would like to prioritize that. But if you thing we can close this one quickly, the let’s do it

Thanks

**Comment by orlando** [comment]
Closing this as we are leaving the current dispute-tools repo in maintenance mode
