### ISSUE TITLE
Establish logging conventions

### ISSUE THREAD

**Issue by saramarcondes** [debtcollective/parent#81]
In gitlab by @shoshber on Feb 21, 2018, 16:40

It will be helpful with debugging and tracking the various services.

It's important to have logging enabled and persisted in the staging environment as it is our first point of contact for the platform outside our development environment. As we being to test more and more in the staging environment, and especially after March, we'll want to be able to know exactly what's going on in staging if things aren't working properly, _without_ having to enable logging or SSH into the staging server itself.

The disputes service is already partially set up with winston and loggly (https://gitlab.com/debtcollective/debtcollective/issues/306):

> [Loggly](https://www.loggly.com/) is a Software-as-a-service (SaaS) for persisting server logs in an easy to see way.
> 
> We have some of the configuration done for it, but we need to make sure that all the developers have access to the staging and production logs. Likewise, we should add logging to all of our API routes and logging to all failed database transactions.
> 
> The latter could be accomplished by overwriting [the default `trx.rollback` method implementation](https://github.com/tgriesser/knex/blob/master/src/transaction.js#L99) with one that sends a log out and then calls the original method.

**Comment by marcondag** [comment]
In gitlab by @shoshber on Feb 21, 2018, 16:42

changed the description

**Comment by shoshber** [comment]
We should look into how to set up alerts for when errors show up in the log. 

This bug affected a user. She reached out to the admins and Ann told is about it, which is how we found out about it. But there was an error in the logs, which should have alerted us to the problem without the user having to take extra steps.
https://gitlab.com/debtcollective/debtcollective/merge_requests/197

[- (1).txt](https://github.com/debtsyndicate/parent/files/1821106/-.1.txt)

**Comment by shoshber** [comment]
Is Loggly or Cloudwatch set up? There are lots of reasons to log that aren't errors.
