### ISSUE TITLE
Media page SSO integration

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#84]
In gitlab by @marcondag on Feb 21, 2018, 17:09

As a debt collective member I want to use the same account across all debt collective services so that I don't have to manage multiple accounts

## Acceptance Criteria

- [ ] WordPress discourse SSO integration is implemented
- [ ] User roles are preserved from Discourse into WordPress
- [ ] If deep linking to a page requiring authentication, the user should be redirected to that page after the authentication process is completed with discourse

**Comment by orlando** [comment]
Media page won't be used by users, only by admins. I'll put this as low priority but is not a blocker for May release

**Comment by orlando** [comment]
I'll close this to clean the backlog
