### ISSUE TITLE
Prevent viewing a dispute-tool from creating a new dispute

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#91]
We need to offset the creation of a dispute until after the member has selected an option or submitted the form for the first time. Otherwise the admin panel becomes filled with never touched disputes. Alternatively, we can also set an initial status that would be excluded from the admin panel and change it to the first status only after the member has added actual information or chosen an option.

**Comment by orlando** [comment]
This is fixed in the current version and will be in the new one. The solution was to present a page before creating the Dispute for Dispute tools that don't have options, like *Dispute Any Debt in Collections*
