### ISSUE TITLE
Integrate Sentry into the Dispute tools, so we get error notifications

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#93]
So we can have more visibility of the errors that are happning in the platform 

## Acceptance Criteria

* [x] Integrate https://github.com/getsentry/raven-js library into the Dispute Tools app
* [x] Add error reporting in the `catch` branch of all promises that are not expected errors (ex. emails and dispute renderers)

**Comment by orlando** [comment]
@marcondag is this one done?

**Comment by marcondag** [comment]
Yup! Went in with the Email stuff two weeks ago.


On Wed, Apr 4, 2018, at 12:51 PM, Orlando Del Aguila wrote:
> @marcondag[1] is this one done?


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/marcondag
  2. https://github.com/debtcollective/parent/issues/93#issuecomment-378669347
