### ISSUE TITLE
Add retrieving user information from Discourse

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#97]
The SSO process allows us to obtain information about the current user through the JWT. However, we cannot currently query Discourse for information about any arbitrary user. This results in us not having access to critical user information on the front end that dispute administrators would like to have, like current emails, current phone numbers, etc. 

## Acceptance Criteria

- [x] Able to query Discourse from Dispute Tools for user information by some identifier
- [x] Current member data is displayed in the dispute administrators panel

**Comment by marcondag** [comment]
Blocked by #10 as we cannot display all the user information we want until it exists 🙂

**Comment by orlando** [comment]
I created #117 as a follow up for this ticket
